#ifndef _PERMISSIONS_H
#define _PERMISSIONS_H

enum PERMISSIONS{
	REGISTER_EMPLOYEE = 1,
	REGISTER_PATIENT  = 2,
	DELETE 		  = 3,
	UPDATE_INFOS 	  = 4,
	REGISTER_DRUG	  = 5,
	REGISTER_ORGAN    = 6,
	MAKE_PROCEDURE 	  = 7
};

#endif
